language: php

sudo: true

addons:
  firefox: "47.0.1"
  postgresql: "9.4"

services:
- postgresql

cache:
  directories:
  - $HOME/.composer/cache
  - $HOME/.npm

php:
- 7.2

env:
  matrix:
  - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE

before_install:
- phpenv config-rm xdebug.ini
- nvm install 8.9
- nvm use 8.9
- touch cli/config.php # Phpunit tests expect this file to be present
- cd ../..
- composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
- export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
- moodle-plugin-ci install

script:
- moodle-plugin-ci phplint
#- moodle-plugin-ci phpcpd
- moodle-plugin-ci phpmd
#- moodle-plugin-ci codechecker
#- moodle-plugin-ci validate
- moodle-plugin-ci savepoints
- moodle-plugin-ci mustache
#- moodle-plugin-ci grunt
#- moodle-plugin-ci phpdoc
- moodle-plugin-ci phpunit
- moodle-plugin-ci behat
